name: Release - Build & Redeploy

on:
  push:
    branches:
      - 'feature/*'

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.103
      - name: dotnet build & test
        run: dotnet build src/backend/GoogleForADay.Services.Api/GoogleForADay.Services.Api.csproj
#      - run: dotnet test src/backend/GoogleForADay.Tests/GoogleForADay.Tests.csproj

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    needs: [test]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.103

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} 
             -p ${{ secrets.DOCKER_PASS }}

      - name: Build docker images
        run: docker build -t $REPO-backend:${GITHUB_SHA::8} src/backend

      - name: Publish Docker images
        run: docker push $REPO-backend

#  redeploy:
#    name: Redeploy webhook call
#    runs-on: ubuntu-18.04
#    needs: [docker]
#    steps:
#      - name: Deploy docker container webhook
#        uses: joelwmale/webhook-action@master
#        env:
#          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
#          data: "{ 'myField': 'myFieldValue'}"